apiVersion: v1
description: Cloud Proivder of Keepalived to support LoadBalancer type of service
name: keepalived
maintainers:
- name: IBM Cloud Private
sources:
- https://github.com/IBM/charts/tree/master/stable
tillerVersion: '>=2.4.0'
version: 0.1.0
