apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: mongoprom
spec:
  match: context.protocol == "tcp"
         && destination.service.host == "mongodb.istio-lab.svc.cluster.local"
  actions:
  - handler: mongohandler
    instances:
    - mongoreceivedbytes
    - mongosentbytes
