apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRoleBinding
metadata:
  name: bind-productpage-viewer
spec:
  subjects:
  - user: "*"
  - properties:
      source.namespace: "istio-lab"
  roleRef:
    kind: ServiceRole
    name: "productpage-viewer"
