apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRole
metadata:
  name: details-reviews-viewer
spec:
  rules:
  - services: ["details.istio-lab.svc.cluster.local","reviews.istio-lab.svc.cluster.local"]
    methods: ["GET"]
