apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRoleBinding
metadata:
  name: bind-details-reviews-viewer
spec:
  subjects:
  - user: "cluster.local/ns/istio-lab/sa/bookinfo-productpgae"
  roleRef:
    kind: ServiceRole
    name: "details-reviews-viewer"
